# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build with Gradle

on:
  workflow_dispatch:
    inputs:
      cloptions:
        description: gradlew commandline options
        required: true
        default: '-S'
        type: choice
        # -S: --full-stacktrace, very verbose (= --full-stacktrace)
        options:
          - '-S'
          - '-S --info'
  
  push:
    branches: [ "master", "preview", "feature/**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-15-intel, windows-latest]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Determine project version
        id: version
        shell: bash
        run: |
          # Extract the version from gradle.properties, removing any trailing whitespace
          PROJECT_VERSION=$(sed -n 's/^version *= *\([a-zA-Z0-9.-]*\) *$/\1/p' gradle.properties | sed 's/[[:space:]]*$//')
          if [[ "${PROJECT_VERSION}" == *-SNAPSHOT ]]; then
            isSnapshotVersion=true
            echo "isSnapshotVersion=true" >> $GITHUB_OUTPUT
          else
            isSnapshotVersion=false
            echo "isSnapshotVersion=false" >> $GITHUB_OUTPUT
          fi
          BUILD_VERSION="${PROJECT_VERSION}"
          if [[    "${{ github.ref }}" == "refs/heads/preview"
                && "${isSnapshotVersion}" == "true" ]]; then
            VERSION_INSERT=preview
          elif [[    "${{ github.ref }}" != "refs/heads/master"
                  && "${{ github.ref }}" != "refs/heads/main"
                  && "${isSnapshotVersion}" == "true" ]]; then
            # Use short SHA as version insert
            SHA=${{ github.sha }}
            # Take first 7 digits as short sha
            SHA_SHORT=${SHA::7}
            VERSION_INSERT=${SHA_SHORT}
          fi
          if [[ -n "${VERSION_INSERT}" ]]; then
            # 1.0.0-SNAPSHOT -> 1.0.0-${VERSION_INSERT}-SNAPSHOT
            BUILD_VERSION="${PROJECT_VERSION%*-SNAPSHOT}-${VERSION_INSERT}-SNAPSHOT"
          fi
          echo "PROJECT_VERSION is: '${PROJECT_VERSION}'"
          echo "BUILD_VERSION is:   '${BUILD_VERSION}'"
          echo "originalProjectVersion=${PROJECT_VERSION}" >> $GITHUB_OUTPUT
          echo "currentBuildVersion=${BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Log project version
        run: |
          echo "Project version: '${{ steps.version.outputs.originalProjectVersion }}'"
          echo "Build version:   '${{ steps.version.outputs.currentBuildVersion }}'"
          echo "Is Snapshot:     ${{ steps.version.outputs.isSnapshotVersion }}"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: |
                        8
                        17
                        21
          distribution: zulu
          cache: gradle

      #- name: Build with Gradle
      #  uses: gradle/actions/setup-gradle@v5
      #  with:
      #    arguments: test

      - name: Build
        id: build
        shell: bash
        run: |
          [[ -z "${{ github.event.inputs.cloptions }}" ]] && options="-S" || options="${{ github.event.inputs.cloptions }}"
          # Continue on failed command:
          set +e
          ./gradlew build ${options} -Pversion=${{ steps.version.outputs.currentBuildVersion }}
          if [[ "$?" == "0" ]]; then
            echo "isOk=true" >> $GITHUB_OUTPUT
            echo "Build SUCCEEDED"
          else 
            echo "isOk=false" >> $GITHUB_OUTPUT
            echo "Build FAILED"
          fi
          # Abort immediately on failed command:
          set -e

      - name: Deploy Snapshot
        id: deploy
        if: ${{    steps.version.outputs.isSnapshotVersion == 'true'
                && steps.build.outputs.isOk == 'true'
                && github.event_name != 'pull_request'
             }}
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          echo "Deploy to Maven Central Snapshots ..."
          set +e
          ./gradlew publish jreleaserDeploy -S --info -Pversion=${{ steps.version.outputs.currentBuildVersion }}
          if [[ "$?" == "0" ]]; then
            echo "isOk=true" >> $GITHUB_OUTPUT
            echo "Deploy SUCCEEDED"
          else 
            echo "isOk=false" >> $GITHUB_OUTPUT
            echo "Deploy FAILED"
          fi
          set -e

      #- name: Conditional step for releases only
      #  if: steps.version.outputs.isSnapshotVersion == 'false'
      #  run: echo "This is a release version!"

      - name: Attach build
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            build

      - name: Fail job if build or deploy failed
        # Note: deploy job is optional - so we check explicitely for 'false'!
        if: ${{    steps.build.outputs.isOk != 'true'
                || steps.deploy.outputs.isOk == 'false'
             }}
        shell: bash
        run: |
          echo "Enforce job failure since build or deploy step failed."
          exit 1
